items = [
    {
        "rank": 0,
        "title": "Starship will attempt a launch this Friday",
        "url": "https://www.fly.faa.gov/adv/adv_spt.jsp",
        "comhead": "fly.faa.gov",
        "score": "406",
        "author": "LorenDB",
        "author_link": "https://news.ycombinator.com/user?id=LorenDB",
        "submit_time": datetime.datetime(2023, 11, 14, 2, 0, 31, 404955),
        "comment_cnt": "246",
        "comment_url": "https://news.ycombinator.com/item?id=38257794",
    },
    {
        "rank": 1,
        "title": "A coder considers the waning days of the craft",
        "url": "https://www.newyorker.com/magazine/2023/11/20/a-coder-considers-the-waning-days-of-the-craft",
        "comhead": "newyorker.com",
        "score": "304",
        "author": "jsomers",
        "author_link": "https://news.ycombinator.com/user?id=jsomers",
        "submit_time": datetime.datetime(2023, 11, 14, 1, 0, 31, 405311),
        "comment_cnt": "493",
        "comment_url": "https://news.ycombinator.com/item?id=38257094",
    },
    {
        "rank": 2,
        "title": "Designing a programming language to speedrun Advent of Code",
        "url": "https://blog.vero.site/post/noulith",
        "comhead": "blog.vero.site",
        "score": "45",
        "author": "polyrand",
        "author_link": "https://news.ycombinator.com/user?id=polyrand",
        "submit_time": datetime.datetime(2023, 11, 14, 6, 0, 31, 405539),
        "comment_cnt": "12",
        "comment_url": "https://news.ycombinator.com/item?id=38255808",
    },
    {
        "rank": 3,
        "title": "Building an occupancy sensor with a $5 ESP32 and a serverless DB",
        "url": "https://matthew.science/posts/occupancy/",
        "comhead": "matthew.science",
        "score": "530",
        "author": "sodality2",
        "author_link": "https://news.ycombinator.com/user?id=sodality2",
        "submit_time": datetime.datetime(2023, 11, 13, 18, 0, 31, 405767),
        "comment_cnt": "173",
        "comment_url": "https://news.ycombinator.com/item?id=38252566",
    },
    {
        "rank": 4,
        "title": 'Inequalities, convergence, and continuity as "special deals"',
        "url": "https://terrytao.wordpress.com/2023/06/04/inequalities-convergence-and-continuity-as-special-deals/",
        "comhead": "terrytao.wordpress.com",
        "score": "14",
        "author": "bdr",
        "author_link": "https://news.ycombinator.com/user?id=bdr",
        "submit_time": datetime.datetime(2023, 11, 14, 7, 0, 31, 405987),
        "comment_cnt": "0",
        "comment_url": None,
    },
    {
        "rank": 5,
        "title": "Low current around roots boosts plant growth",
        "url": "https://www.nature.com/articles/d44151-023-00162-5",
        "comhead": "nature.com",
        "score": "145",
        "author": "bookofjoe",
        "author_link": "https://news.ycombinator.com/user?id=bookofjoe",
        "submit_time": datetime.datetime(2023, 11, 13, 23, 0, 31, 406214),
        "comment_cnt": "50",
        "comment_url": "https://news.ycombinator.com/item?id=38256137",
    },
    {
        "rank": 6,
        "title": "Nepal bans TikTok and says it disrupts social harmony",
        "url": "https://apnews.com/article/nepal-tiktok-ban-social-media-854846a42ef566fa296ddaacd0099447",
        "comhead": "apnews.com",
        "score": "399",
        "author": "thunderbong",
        "author_link": "https://news.ycombinator.com/user?id=thunderbong",
        "submit_time": datetime.datetime(2023, 11, 14, 0, 0, 31, 406417),
        "comment_cnt": "207",
        "comment_url": "https://news.ycombinator.com/item?id=38256810",
    },
    {
        "rank": 7,
        "title": "Hacking Google Bard – From Prompt Injection to Data Exfiltration",
        "url": "https://embracethered.com/blog/posts/2023/google-bard-data-exfiltration/",
        "comhead": "embracethered.com",
        "score": "363",
        "author": "goranmoomin",
        "author_link": "https://news.ycombinator.com/user?id=goranmoomin",
        "submit_time": datetime.datetime(2023, 11, 13, 17, 0, 31, 406639),
        "comment_cnt": "137",
        "comment_url": "https://news.ycombinator.com/item?id=38251957",
    },
    {
        "rank": 8,
        "title": "Maxar's Open Satellite Feed",
        "url": "https://tech.marksblogg.com/maxar-open-data-free-satellite-imagery.html",
        "comhead": "tech.marksblogg.com",
        "score": "123",
        "author": "ingve",
        "author_link": "https://news.ycombinator.com/user?id=ingve",
        "submit_time": datetime.datetime(2023, 11, 13, 23, 0, 31, 406940),
        "comment_cnt": "17",
        "comment_url": "https://news.ycombinator.com/item?id=38248497",
    },
    {
        "rank": 9,
        "title": "The Best Timed Shot in TV History (Probably)",
        "url": "https://greekreporter.com/2023/11/09/best-timed-shot-tv-history/",
        "comhead": "greekreporter.com",
        "score": "63",
        "author": "rmason",
        "author_link": "https://news.ycombinator.com/user?id=rmason",
        "submit_time": datetime.datetime(2023, 11, 14, 4, 0, 31, 407173),
        "comment_cnt": "42",
        "comment_url": "https://news.ycombinator.com/item?id=38247543",
    },
    {
        "rank": 10,
        "title": "Many popular houses in 1920s L.A. were part of a scam",
        "url": "https://www.atlasobscura.com/articles/los-angeles-home-scam",
        "comhead": "atlasobscura.com",
        "score": "32",
        "author": "vo2maxer",
        "author_link": "https://news.ycombinator.com/user?id=vo2maxer",
        "submit_time": datetime.datetime(2023, 11, 14, 2, 0, 31, 407385),
        "comment_cnt": "16",
        "comment_url": "https://news.ycombinator.com/item?id=38257813",
    },
    {
        "rank": 11,
        "title": "Lets build an Amiga Network Adapter [video]",
        "url": "https://www.youtube.com/watch?v=sx9X0bjj6_8",
        "comhead": "youtube.com",
        "score": "5",
        "author": "doener",
        "author_link": "https://news.ycombinator.com/user?id=doener",
        "submit_time": datetime.datetime(2023, 11, 14, 8, 0, 31, 407583),
        "comment_cnt": "0",
        "comment_url": None,
    },
    {
        "rank": 12,
        "title": "The laptop that won't die",
        "url": "https://clivethompson.medium.com/the-laptop-that-wont-die-0c478c3fe46c",
        "comhead": "clivethompson.medium.com",
        "score": "105",
        "author": "ShikhaM",
        "author_link": "https://news.ycombinator.com/user?id=ShikhaM",
        "submit_time": datetime.datetime(2023, 11, 14, 1, 0, 31, 407779),
        "comment_cnt": "148",
        "comment_url": "https://news.ycombinator.com/item?id=38257284",
    },
    {
        "rank": 13,
        "title": "Infinite Context LLMs: Going Beyond RAG with Extended Minds",
        "url": "https://blog.normalcomputing.ai/posts/2023-09-12-supersizing-transformers/supersizing-transformers.html",
        "comhead": "blog.normalcomputing.ai",
        "score": "49",
        "author": "telotortium",
        "author_link": "https://news.ycombinator.com/user?id=telotortium",
        "submit_time": datetime.datetime(2023, 11, 14, 0, 0, 31, 407970),
        "comment_cnt": "0",
        "comment_url": None,
    },
    {
        "rank": 14,
        "title": "Black goo is the new oscilloscope: Love Hultén's ferrofluid synths",
        "url": "https://cdm.link/2023/11/black-goo-ferrofluid-synths/",
        "comhead": "cdm.link",
        "score": "252",
        "author": "glitcher",
        "author_link": "https://news.ycombinator.com/user?id=glitcher",
        "submit_time": datetime.datetime(2023, 11, 13, 16, 0, 31, 408162),
        "comment_cnt": "54",
        "comment_url": "https://news.ycombinator.com/item?id=38250913",
    },
    {
        "rank": 15,
        "title": "Smarter summaries with finetuning GPT-3.5 and chain of density",
        "url": "https://jxnl.github.io/instructor/blog/2023/11/05/chain-of-density/",
        "comhead": "jxnl.github.io",
        "score": "198",
        "author": "ivanleomk",
        "author_link": "https://news.ycombinator.com/user?id=ivanleomk",
        "submit_time": datetime.datetime(2023, 11, 13, 17, 0, 31, 408360),
        "comment_cnt": "31",
        "comment_url": "https://news.ycombinator.com/item?id=38251842",
    },
    {
        "rank": 16,
        "title": "Android App Devs now require 20 people to test before publishing to Play Store",
        "url": "https://techcrunch.com/2023/11/09/google-play-tightens-up-rules-for-android-app-developers-to-require-testing-increased-app-review/",
        "comhead": "techcrunch.com",
        "score": "176",
        "author": "robertwt7",
        "author_link": "https://news.ycombinator.com/user?id=robertwt7",
        "submit_time": datetime.datetime(2023, 11, 14, 3, 0, 31, 408548),
        "comment_cnt": "103",
        "comment_url": "https://news.ycombinator.com/item?id=38258101",
    },
    {
        "rank": 17,
        "title": "C++ Lambda Idioms (2022) [video]",
        "url": "https://www.youtube.com/watch?v=xBAduq0RGes",
        "comhead": "youtube.com",
        "score": "40",
        "author": "lichtenberger",
        "author_link": "https://news.ycombinator.com/user?id=lichtenberger",
        "submit_time": datetime.datetime(2023, 11, 13, 23, 0, 31, 408730),
        "comment_cnt": "0",
        "comment_url": None,
    },
    {
        "rank": 18,
        "title": "HTML Web Components",
        "url": "https://blog.jim-nielsen.com/2023/html-web-components/",
        "comhead": "blog.jim-nielsen.com",
        "score": "396",
        "author": "goranmoomin",
        "author_link": "https://news.ycombinator.com/user?id=goranmoomin",
        "submit_time": datetime.datetime(2023, 11, 13, 16, 0, 31, 408893),
        "comment_cnt": "205",
        "comment_url": "https://news.ycombinator.com/item?id=38251330",
    },
    {
        "rank": 19,
        "title": "Unlogged (YC S22) Is Hiring a founding back end engineer",
        "url": "item?id=38257499",
        "comhead": "item",
        "score": "0",
        "author": None,
        "author_link": None,
        "submit_time": datetime.datetime(2023, 11, 14, 2, 0, 31, 409061),
        "comment_cnt": "0",
        "comment_url": None,
    },
    {
        "rank": 20,
        "title": "Jorge Luis Borges and the Labyrinths of Copyright",
        "url": "https://www.washingtonpost.com/business/2023/07/04/jorge-luis-borges-estate-overcomes-copyright-qualms-with-recognized-heirs/8f8d679e-1a23-11ee-be41-a036f4b098ec_story.html",
        "comhead": "washingtonpost.com",
        "score": "24",
        "author": "bryanrasmussen",
        "author_link": "https://news.ycombinator.com/user?id=bryanrasmussen",
        "submit_time": datetime.datetime(2023, 11, 14, 3, 0, 31, 409200),
        "comment_cnt": "8",
        "comment_url": "https://news.ycombinator.com/item?id=38249587",
    },
    {
        "rank": 21,
        "title": "Researchers identify 'switch' to activate cancer cell death",
        "url": "https://health.ucdavis.edu/news/headlines/researchers-identify-switch-to-activate-cancer-cell-death/2023/10",
        "comhead": "health.ucdavis.edu",
        "score": "143",
        "author": "DocFeind",
        "author_link": "https://news.ycombinator.com/user?id=DocFeind",
        "submit_time": datetime.datetime(2023, 11, 13, 18, 0, 31, 409380),
        "comment_cnt": "57",
        "comment_url": "https://news.ycombinator.com/item?id=38252947",
    },
    {
        "rank": 22,
        "title": "Cosmological galaxy formation simulation software",
        "url": "https://www.tng-project.org/about/",
        "comhead": "tng-project.org",
        "score": "58",
        "author": "krpl",
        "author_link": "https://news.ycombinator.com/user?id=krpl",
        "submit_time": datetime.datetime(2023, 11, 13, 19, 0, 31, 409539),
        "comment_cnt": "7",
        "comment_url": "https://news.ycombinator.com/item?id=38252449",
    },
    {
        "rank": 23,
        "title": "Show HN: SirixDB  –\xa0Bitemporal binary JSON database system and event store",
        "url": "https://github.com/sirixdb/sirix",
        "comhead": "github.com/sirixdb",
        "score": "88",
        "author": "lichtenberger",
        "author_link": "https://news.ycombinator.com/user?id=lichtenberger",
        "submit_time": datetime.datetime(2023, 11, 13, 18, 0, 31, 409708),
        "comment_cnt": "10",
        "comment_url": "https://news.ycombinator.com/item?id=38252963",
    },
    {
        "rank": 24,
        "title": "Days of The Jackal: how Andrew Wylie turned serious literature into big business",
        "url": "https://www.theguardian.com/books/2023/nov/09/andrew-wylie-agency-days-of-the-jackal-serious-literature-big-business",
        "comhead": "theguardian.com",
        "score": "42",
        "author": "lermontov",
        "author_link": "https://news.ycombinator.com/user?id=lermontov",
        "submit_time": datetime.datetime(2023, 11, 14, 2, 0, 31, 409866),
        "comment_cnt": "4",
        "comment_url": "https://news.ycombinator.com/item?id=38242992",
    },
    {
        "rank": 25,
        "title": "Google pays Apple 36% of the revenue it earns from searches in Safari",
        "url": "https://www.bloomberg.com/news/articles/2023-11-13/apple-gets-36-of-google-revenue-from-search-deal-witness-says",
        "comhead": "bloomberg.com",
        "score": "155",
        "author": "mfiguiere",
        "author_link": "https://news.ycombinator.com/user?id=mfiguiere",
        "submit_time": datetime.datetime(2023, 11, 13, 19, 0, 31, 410030),
        "comment_cnt": "181",
        "comment_url": "https://news.ycombinator.com/item?id=38253384",
    },
    {
        "rank": 26,
        "title": "Ship Shape",
        "url": "https://www.canva.dev/blog/engineering/ship-shape/",
        "comhead": "canva.dev",
        "score": "304",
        "author": "SerCe",
        "author_link": "https://news.ycombinator.com/user?id=SerCe",
        "submit_time": datetime.datetime(2023, 11, 13, 13, 0, 31, 410193),
        "comment_cnt": "79",
        "comment_url": "https://news.ycombinator.com/item?id=38249214",
    },
    {
        "rank": 27,
        "title": "Panama Canal is so congested that one ship owner paid $4M to skip the line",
        "url": "https://fortune.com/2023/11/08/panama-canal-congestion-record-4-million-skip-line/",
        "comhead": "fortune.com",
        "score": "216",
        "author": "mfiguiere",
        "author_link": "https://news.ycombinator.com/user?id=mfiguiere",
        "submit_time": datetime.datetime(2023, 11, 13, 20, 0, 31, 410375),
        "comment_cnt": "220",
        "comment_url": "https://news.ycombinator.com/item?id=38254353",
    },
    {
        "rank": 28,
        "title": "Slow-Scan Television",
        "url": "https://en.wikipedia.org/wiki/Slow-scan_television",
        "comhead": "en.wikipedia.org",
        "score": "105",
        "author": "bookofjoe",
        "author_link": "https://news.ycombinator.com/user?id=bookofjoe",
        "submit_time": datetime.datetime(2023, 11, 13, 17, 0, 31, 410535),
        "comment_cnt": "21",
        "comment_url": "https://news.ycombinator.com/item?id=38251935",
    },
    {
        "rank": 29,
        "title": "The NYPD is using drones 3 times more than it did last year",
        "url": "https://gothamist.com/news/the-nypd-is-using-drones-3-times-more-than-it-did-last-year",
        "comhead": "gothamist.com",
        "score": "130",
        "author": "jbegley",
        "author_link": "https://news.ycombinator.com/user?id=jbegley",
        "submit_time": datetime.datetime(2023, 11, 13, 16, 0, 31, 410696),
        "comment_cnt": "147",
        "comment_url": "https://news.ycombinator.com/item?id=38251032",
    },
]
